version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/cached"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/cached_annotation"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
