name: cached
description: Dart package with build-in code generation. Simplifies and speedup creation of cache mechanism for dart classes.
version: 1.0.3
repository: https://github.com/Iteo/cached
issue_tracker: https://github.com/Iteo/cached/issues
homepage: https://github.com/Iteo/cached
documentation: https://github.com/Iteo/cached/blob/master/packages/cached/README.md

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  analyzer: ^4.1.0
  build: ^2.3.0
  cached_annotation: ^1.0.0
  collection: ^1.16.0
  meta: ^1.7.0
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.1.11
  lint: ^1.8.2
  path: ^1.8.2
  source_gen_test: ^1.0.3
  test: ^1.21.1