name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_annotation: ^1.6.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.4.6
  cached: ^1.6.3
  lints: ^2.1.1


