name: cached_annotation
description: Annotation package for cached lib
version: 1.4.0
repository: https://github.com/Iteo/cached
issue_tracker: https://github.com/Iteo/cached/issues
homepage: https://github.com/Iteo/cached
documentation: https://github.com/Iteo/cached/blob/master/packages/cached/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.8.2
