name: persistent_storage_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_annotation:
    path: '../../../cached_annotation'
  hive: ^2.2.3
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.4.6
  cached:
    path: '../../'
  linteo: ^1.0.1
  hive_generator: 2.0.1
