name: persistent_storage_example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cached_annotation: ^1.5.0
  hive: ^2.2.3
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.3.2
  cached: ^1.5.1
  linteo: ^1.0.1
  hive_generator: 2.0.0
