name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_annotation: ^1.5.0
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.10
  cached: ^1.5.0
  lints: ^2.0.1
