name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:

dev_dependencies:
  build_runner: ^2.1.10
  cached_annotation:
    path: ../../cached_annotation
  cached:
    path: ../.
  lints: ^1.0.0
